version: '3'

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: yellowtaxi
      MYSQL_ROOT_PASSWORD: helloworld
    ports:
      - 3308:3306

  admin:    
    image: adminer    
    ports:      
      - "8080:8080"